/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * @brief This project will toggle the User LED on the STM32F407G-DISC1 board
 * using BareMetal along with FreeRTOS approach
 *
 * User LED: User LD3: Orange LED is a user LED connected to the I/O PD13 of the
 * STM32F407VGT6 MCU
 *
 * GPIO Port: Port D
 * GPIO Pin:  Pin 13
 */

